/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-10-17 06:40:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class createAccountPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <title>Create Employee Account</title>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <h1>Create Employee Account</h1>\n");
      out.write("    <form method = \"post\">\n");
      out.write("    <table style=\"width: 50%\">\n");
      out.write("        <tr>\n");
      out.write("            <td>EmployeeID </td>\n");
      out.write("            <td><input type = \"text\" name = \"employeeId\" required/></td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>Name: </td>\n");
      out.write("            <td><input type = \"text\" name = \"name\" required/></td>\n");
      out.write("        </tr>\n");
      out.write("    \n");
      out.write("        <tr>\n");
      out.write("            <td>UserName: </td>\n");
      out.write("            <td><input type = \"text\" name = \"user_name\" required/></td>\n");
      out.write("        </tr>\n");
      out.write("    \n");
      out.write("        <tr>\n");
      out.write("            <td>Password: </td>\n");
      out.write("            <td><input type = \"text\" name = \"password\" required/></td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>Re-Enter Password: </td>\n");
      out.write("            <td><input type = \"text\" name = \"re_password\" required/></td>\n");
      out.write("        </tr>\n");
      out.write("    \n");
      out.write("        <tr><td>Enter your role: </td></tr>\n");
      out.write("        <tr><td>1. Hotel Manger</td></tr>\n");
      out.write("        <tr><td>2. Housekeeper</td></tr>\n");
      out.write("        <tr><td>3. Front Desk</td></tr>\n");
      out.write("        <tr><td>4. Security</td></tr>\n");
      out.write("        <tr><td>5. Maintenance & Bellhops</td></tr>\n");
      out.write("        <tr><td>6. Others</td></tr>\n");
      out.write("        <tr><td><input type = \"text\" name = \"role\" required></td></tr>\n");
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>Hotel Location: </td>\n");
      out.write("            <td><input type = \"text\" name = \"hotel_location\" required/></td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>Hotel Name: </td>\n");
      out.write("            <td><input type = \"text\" name = \"hotel_name\" required/></td>\n");
      out.write("        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </table>\n");
      out.write("    <input type=\"submit\" value=\"Submit\" />\n");
      out.write("    </form>\n");
      out.write("    ");

    if ("POST".equalsIgnoreCase(request.getMethod())) {
        String id = request.getParameter("employeeId");
        int nId = Integer.parseInt(id);
        String name = request.getParameter("name");
        String userName = request.getParameter("user_name");
        String userPassword = request.getParameter("password");
        String rePassword = request.getParameter("re_password");
        String role = request.getParameter("role");
        String hotelLocation = request.getParameter("hotel_location");
        String hotelName = request.getParameter("hotel_name");

        
        if (userPassword != null && rePassword != null && userPassword.equals(rePassword)) {
            int roleN = Integer.parseInt(role);
            if (roleN >= 1 && roleN <= 6) {
    
      out.write("\n");
      out.write("                <p>Your account is created</p>\n");
      out.write("    ");
 
            String user;
            user = "root";
            String password = "Ken30526296@";
            PreparedStatement preparedStatement = null;
            try {
        
            java.sql.Connection con; 
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project?autoReconnect=true&useSSL=false",user, password);

            String sql = "INSERT INTO Employee (ID, HotelLocation, HotelName, Name, Role, Username, Password) VALUES (?, ?, ?, ?, ?, ?, ?)";
            preparedStatement = con.prepareStatement(sql);
            preparedStatement.setInt(1, nId);
            preparedStatement.setString(2, hotelLocation);
            preparedStatement.setString(3, hotelName);
            preparedStatement.setString(4, name);
            preparedStatement.setString(5, role);
            preparedStatement.setString(6, userName);    
            preparedStatement.setString(7, userPassword);

            preparedStatement.executeUpdate();
        
            out.println("Initial entries in table \"Employee\": <br/>");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM Employee");
            while (rs.next()) {
                out.println(rs.getInt(1) + "    " + rs.getString(2) + "    " + rs.getString(3) + "    " + rs.getString(4) + "    " + 
                rs.getString(5) + "    " + rs.getString(6) + "    " + rs.getString(7) +
                "<br/><br/>");
            }
            rs.close();
            stmt.close();
            con.close();
        } 
        catch(SQLException e) { 
            out.println("SQLException caught: " + e.getMessage()); 
        }
    
      out.write("\n");
      out.write("    ");

            } 
            else {
    
      out.write("\n");
      out.write("                <p>Invalid role number</p>\n");
      out.write("    ");

            }
        } 
        else {
    
      out.write("\n");
      out.write("            <p>Passwords do not match</p>\n");
      out.write("    ");

        }
    }
    
      out.write("\n");
      out.write("\n");
      out.write("    \n");
      out.write("  </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
