/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-12-06 00:25:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.time.*;

public final class revenuePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jspf", Long.valueOf(1701820678179L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.time");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("      <title>Revenue Page</title>\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\">\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"navbar.css\"/>\r\n");
      out.write("      <style>\r\n");
      out.write("          .header-text{\r\n");
      out.write("              background-color: lightblue;\r\n");
      out.write("              font-size: 100px;\r\n");
      out.write("              text-align: center;\r\n");
      out.write("            }\r\n");
      out.write("  \r\n");
      out.write("          .hotel-location-text{\r\n");
      out.write("              font-size: 24px;\r\n");
      out.write("              text-align: start;\r\n");
      out.write("              padding-bottom: 16px;\r\n");
      out.write("          }\r\n");
      out.write("          .table{\r\n");
      out.write("              width: 100%;\r\n");
      out.write("          }\r\n");
      out.write("          .dollarSign{\r\n");
      out.write("            align: left;\r\n");
      out.write("          }\r\n");
      out.write("      </style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("<nav class=\"navbar is-transparent\" role=\"navigation\" aria-label=\"main navigation\">\n");
      out.write("  <div id=\"navbarBasicExample\" class=\"navbar-menu\">\n");
      out.write("    <div class=\"navbar-start\">\n");
      out.write("      <a class=\"navbar-item\" href=\"Menu.jsp\">\n");
      out.write("        <span class=\"icon-text\">\n");
      out.write("          <span class=\"icon\">\n");
      out.write("            <i class=\"fas fa-home\"></i>\n");
      out.write("          </span>\n");
      out.write("          <span>Home</span>\n");
      out.write("        </span>\n");
      out.write("      </a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"navbar-end\">\n");
      out.write("      <div class=\"navbar-item\">\n");
      out.write("        <div class=\"buttons\">\n");
      out.write("          <a class=\"navbar-item\" href=\"hotelsPage.jsp\">\n");
      out.write("            Hotels\n");
      out.write("          </a>\n");
      out.write("          <a class=\"navbar-item\" href=\"shiftPage.jsp\">\n");
      out.write("            Shift\n");
      out.write("          </a>\n");
      out.write("          <a class=\"button is-light\" onclick=\"logOut()\">\n");
      out.write("            Log Out\n");
      out.write("          </a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("      <h1 class=\"header-text\">Revenue</h1>\r\n");
      out.write("      <form method=\"post\" action=\"\">\r\n");
      out.write("        <input class=\"button is-light\" style=\"margin-top: 2px; margin-left: 48px;\" type=\"submit\" name=\"sortbyDate\" value=\"Sort by date\">\r\n");
      out.write("      </form>\r\n");
      out.write(" ");

    String displayRevenue = "select * from Revenue";
    String displayTotal = "select SUM(Credit) from Revenue";
    String displayIncome;
    String displayExpense;
    String user = "root";
    String pass = "Ken30526296@";
    boolean sortByClicked = false;

    String buttonClicked = request.getParameter("sortbyDate");

    if ("Sort by date".equalsIgnoreCase(buttonClicked)) {
        displayRevenue = "select * from Revenue order by Date";
    }

    try {
        java.sql.Connection con;
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Project?autoReconnect=true&useSSL=false", user, pass);
        
        PreparedStatement ps1 = con.prepareStatement(displayRevenue);
        PreparedStatement ps2 = con.prepareStatement(displayTotal);
        ResultSet rs1 = ps1.executeQuery();
        ResultSet rs2 = ps2.executeQuery();
        
        rs2.next();
        int total = rs2.getInt(1);
    
      out.write("\r\n");
      out.write("    <table class=\"table is-bordered is-striped is-narrow is-hoverable is-fullwidth\" style=\"width: 90%; margin-left: 48px;\">\r\n");
      out.write("      <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>ID</td>\r\n");
      out.write("          <td>Booking Number</td>\r\n");
      out.write("          <td>Date</td>\r\n");
      out.write("          <td>Type</td>\r\n");
      out.write("          <td>Item Name</td>\r\n");
      out.write("          <td align = \"right\">Credit</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("      <tbody>\r\n");
      out.write("        ");
 while(rs1.next()) {
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>");
      out.print( rs1.getInt("ID") );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( rs1.getInt("BookingNumber") );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( rs1.getObject("Date", OffsetDateTime.class) );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( rs1.getString("Type") );
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( rs1.getString("ItemName") );
      out.write("</td>\r\n");
      out.write("          <td align = \"right\"><span class = 'dollarSign'>$</span>");
      out.print( rs1.getInt("Credit") );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </tbody>\r\n");
      out.write("      <tfoot>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>Total</th>\r\n");
      out.write("          <th>$");
      out.print( total );
      out.write("</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </tfoot>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    ");
 

        rs1.close();
        ps1.close();
        rs2.close();
        ps2.close();
        con.close();
    }
    catch (SQLException e) {
        out.println("Exception caught: " + e.getMessage());
    }
    
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        window.onload = function() {\r\n");
      out.write("          const employeeIDon = localStorage.getItem(\"employeeID\");\r\n");
      out.write("          const employeeRoleon = localStorage.getItem(\"employeeRole\");\r\n");
      out.write("          const queryParams = \"?employeeIDon=\" + encodeURIComponent(employeeIDon) + \"&employeeRoleon=\" + encodeURIComponent(employeeRoleon);\r\n");
      out.write("          const targetURL = window.location.pathname + queryParams;\r\n");
      out.write("          if (window.location.search != queryParams) {\r\n");
      out.write("              window.location.href = targetURL;\r\n");
      out.write("          }\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        function logOut(){\r\n");
      out.write("          localStorage.removeItem(\"employeeID\");\r\n");
      out.write("          localStorage.removeItem(\"username\");\r\n");
      out.write("          window.location.href=\"loginPage.jsp\"\r\n");
      out.write("        }\r\n");
      out.write("        function setSortToTrue() {\r\n");
      out.write("          sortByClicked = true;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
